// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enemies.sql

package database

import (
	"context"
)

const getEnemies = `-- name: GetEnemies :many
SELECT id, name, level FROM enemies
`

func (q *Queries) GetEnemies(ctx context.Context) ([]Enemy, error) {
	rows, err := q.db.Query(ctx, getEnemies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enemy
	for rows.Next() {
		var i Enemy
		if err := rows.Scan(&i.ID, &i.Name, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
