// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createInventoryItem = `-- name: CreateInventoryItem :exec
INSERT INTO inventory (item_id, player_id, quantity)
VALUES ($1, $2, $3)
`

type CreateInventoryItemParams struct {
	ItemID   uuid.UUID
	PlayerID uuid.UUID
	Quantity int32
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) error {
	_, err := q.db.Exec(ctx, createInventoryItem, arg.ItemID, arg.PlayerID, arg.Quantity)
	return err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory
WHERE item_id = $1 AND player_id = $2
`

type DeleteInventoryItemParams struct {
	ItemID   uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) DeleteInventoryItem(ctx context.Context, arg DeleteInventoryItemParams) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, arg.ItemID, arg.PlayerID)
	return err
}

const getInventoryByPlayerID = `-- name: GetInventoryByPlayerID :many
SELECT item_id, player_id, quantity FROM inventory
WHERE player_id = $1
`

func (q *Queries) GetInventoryByPlayerID(ctx context.Context, playerID uuid.UUID) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, getInventoryByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(&i.ItemID, &i.PlayerID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
