// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_categories.sql

package database

import (
	"context"
)

const getItemCategories = `-- name: GetItemCategories :many
SELECT id, name FROM item_categories
`

func (q *Queries) GetItemCategories(ctx context.Context) ([]ItemCategory, error) {
	rows, err := q.db.Query(ctx, getItemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemCategory
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
