// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_categories.sql

package database

import (
	"context"
)

const getItemCategoriesByName = `-- name: GetItemCategoriesByName :one
SELECT id, name FROM item_categories
WHERE name = $1
`

func (q *Queries) GetItemCategoriesByName(ctx context.Context, name string) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, getItemCategoriesByName, name)
	var i ItemCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
