// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItems = `-- name: CreateItems :one
INSERT INTO items (name, description, category_id, effect_target, effect_value, value)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, category_id, effect_target, effect_value, value
`

type CreateItemsParams struct {
	Name         string
	Description  string
	CategoryID   int32
	EffectTarget pgtype.Text
	EffectValue  pgtype.Int4
	Value        int32
}

func (q *Queries) CreateItems(ctx context.Context, arg CreateItemsParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItems,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.EffectTarget,
		arg.EffectValue,
		arg.Value,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.EffectTarget,
		&i.EffectValue,
		&i.Value,
	)
	return i, err
}

const deleteItems = `-- name: DeleteItems :exec
DELETE FROM items
`

func (q *Queries) DeleteItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteItems)
	return err
}

const getItemsByCategoryID = `-- name: GetItemsByCategoryID :many
SELECT id, name, description, category_id, effect_target, effect_value, value FROM items
WHERE category_id = $1
`

func (q *Queries) GetItemsByCategoryID(ctx context.Context, categoryID int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.EffectTarget,
			&i.EffectValue,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByName = `-- name: GetItemsByName :one
SELECT id, name, description, category_id, effect_target, effect_value, value FROM items
WHERE name = $1
`

func (q *Queries) GetItemsByName(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemsByName, name)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.EffectTarget,
		&i.EffectValue,
		&i.Value,
	)
	return i, err
}
