// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package database

import (
	"context"
)

const getItems = `-- name: GetItems :many
SELECT id, name, description, category_id, effect_description, effect_target, effect_value, value FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.EffectDescription,
			&i.EffectTarget,
			&i.EffectValue,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByCategoryID = `-- name: GetItemsByCategoryID :many
SELECT id, name, description, category_id, effect_description, effect_target, effect_value, value FROM items
WHERE category_id = $1
`

func (q *Queries) GetItemsByCategoryID(ctx context.Context, categoryID int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.EffectDescription,
			&i.EffectTarget,
			&i.EffectValue,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByName = `-- name: GetItemsByName :one
SELECT id, name, description, category_id, effect_description, effect_target, effect_value, value FROM items
WHERE name = $1
`

func (q *Queries) GetItemsByName(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemsByName, name)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.EffectDescription,
		&i.EffectTarget,
		&i.EffectValue,
		&i.Value,
	)
	return i, err
}
