// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location_directions.sql

package database

import (
	"context"
)

const getLocationDirectionByID = `-- name: GetLocationDirectionByID :many
SELECT location_id, direction, direction_target FROM location_directions
WHERE location_id = $1
`

func (q *Queries) GetLocationDirectionByID(ctx context.Context, locationID int32) ([]LocationDirection, error) {
	rows, err := q.db.Query(ctx, getLocationDirectionByID, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationDirection
	for rows.Next() {
		var i LocationDirection
		if err := rows.Scan(&i.LocationID, &i.Direction, &i.DirectionTarget); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
