// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID           uuid.UUID
	Name         string
	Description  string
	CategoryID   int32
	EffectTarget pgtype.Text
	EffectValue  pgtype.Int4
	Value        int32
}

type ItemCategory struct {
	ID   int32
	Name string
}

type Player struct {
	ID           uuid.UUID
	Name         string
	CurrentExp   pgtype.Int4
	CurrentLevel pgtype.Int4
	MaxHealth    pgtype.Int4
	MaxMana      pgtype.Int4
	Strength     pgtype.Int4
	Defense      pgtype.Int4
	Gold         pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
