// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ItemID   int32
	PlayerID uuid.UUID
	Quantity int32
}

type Item struct {
	ID                int32
	Name              string
	Description       string
	CategoryID        int32
	EffectDescription pgtype.Text
	EffectTarget      pgtype.Text
	EffectValue       pgtype.Int4
	Value             int32
}

type ItemCategory struct {
	ID   int32
	Name string
}

type Location struct {
	ID          int32
	Name        string
	Description string
	HasStore    bool
	CanTeleport bool
}

type LocationDirection struct {
	LocationID      int32
	Direction       string
	DirectionTarget int32
}

type Player struct {
	ID           uuid.UUID
	Name         string
	CurrentExp   int32
	CurrentLevel int32
	Gold         int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       uuid.UUID
	LocationID   int32
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
