// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, user_id)
VALUES ($2, $1)
RETURNING id
`

type CreatePlayerParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.UserID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePlayersByID = `-- name: DeletePlayersByID :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayersByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayersByID, id)
	return err
}

const getPlayersByID = `-- name: GetPlayersByID :one
SELECT id, name, current_exp, current_level, gold, created_at, updated_at, user_id, location_id FROM players
WHERE id = $1
`

func (q *Queries) GetPlayersByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayersByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentExp,
		&i.CurrentLevel,
		&i.Gold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LocationID,
	)
	return i, err
}

const getPlayersByUserID = `-- name: GetPlayersByUserID :many
SELECT id, name FROM players
WHERE user_id = $1
`

type GetPlayersByUserIDRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetPlayersByUserID(ctx context.Context, userID uuid.UUID) ([]GetPlayersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersByUserIDRow
	for rows.Next() {
		var i GetPlayersByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerByID = `-- name: UpdatePlayerByID :exec
UPDATE players
SET current_exp = $2, current_level = $3, gold = $4, location_id = $5, updated_at = NOW()
WHERE id = $1
`

type UpdatePlayerByIDParams struct {
	ID           uuid.UUID
	CurrentExp   int32
	CurrentLevel int32
	Gold         int32
	LocationID   int32
}

func (q *Queries) UpdatePlayerByID(ctx context.Context, arg UpdatePlayerByIDParams) error {
	_, err := q.db.Exec(ctx, updatePlayerByID,
		arg.ID,
		arg.CurrentExp,
		arg.CurrentLevel,
		arg.Gold,
		arg.LocationID,
	)
	return err
}
