CREATE TABLE locations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  min_level INTEGER NOT NULL DEFAULT 1,
  max_level INTEGER NOT NULL DEFAULT 1,
  has_store BOOLEAN NOT NULL DEFAULT FALSE,
  can_teleport BOOLEAN NOT NULL DEFAULT FALSE
);