ALTER TABLE players
ADD COLUMN location_id INTEGER NOT NULL DEFAULT 1 REFERENCES locations(id),
ADD COLUMN weapon_gear INTEGER NOT NULL DEFAULT 0,
ADD COLUMN armor_gear INTEGER NOT NULL DEFAULT 0,
ADD COLUMN accessory_gear INTEGER NOT NULL DEFAULT 0;